- src/net/server/channel/handlers/QuestActionHandler.java
- src/server/quest/MapleQuest.java
This is a small fix for a effect upon quest completion, tested it and it works properly.
> Quest Completion Effect Fix

- 9270017.js
- 9270018.js
- 9270038.js
- 9270041.js
- ariant_castle.js
Fixed:
* Irene, Shalon now check your mesos and only sells you (1) ticket. If you've more than (1) ticket, you can't buy another one.
* Xinga, Kerny, the Pilots, now stating correct places when you're on airplane and airports.
* The portal to get in to Ariant Castle now needs (1) Entry Pass to get in.
> Small Fix on NPCs and Portal.

- .gitignore
- scripts/event/PinkBeanBattle.js
I hope you meant growing and not glowing, because glowing is an interesting word too.
> Fix spelling in PinkBeanBattle Script

- .gitignore
- sql/db_database.sql
- sql/db_drops.sql
- src/client/MapleClient.java
- src/constants/ServerConstants.java
- src/net/server/Server.java
- src/net/server/handlers/login/LoginPasswordHandler.java
- src/tools/BCrypt.java
Added some more changes that I think will be great for the project. Let me know if any of them is bad and we can remove them :)
> Added bcrypt support.

- compile-posix.sh
- launch.sh
Adds support for headless environment compilation and launching in POSIX compliant systems
> POSIX support

- src/net/server/handlers/login/LoginPasswordHandler.java
- To fix the MySQL 5.7 strict mode on LoginPasswordHandler.java
- Added birthday, tempban into SQL query to fix this issue
Please review this code, would like to know more if I did mistake on it, thanks!
> Fix on Auto Register

- scripts/npc/9201123.js
- scripts/npc/9201124.js
- scripts/npc/9201125.js
- scripts/npc/9201126.js
- scripts/npc/9201127.js
* Fixed the 5 Statues in Lith Harbor
* Including check for player's job
> Fixed 5 Statues in Lith Harbor

- src/client/processor/DueyProcessor.java
Fix for receiving items on the 9th day of the month and 9th month of the year.
> Fix for receiving items with duey

- src/scripting/event/EventInstanceManager.java
The monster the Tamming mob not killed on java 8
> Event monster bug

- src/scripting/event/EventInstanceManager.java
- src/scripting/event/EventManager.java
when enter with party
got exeption in with use java 8
> Fix npcs script

- scripts/quest/21401.js
Fix javax.script.ScriptException
---------------------------------------------------------------------
javax.script.ScriptException: sun.org.mozilla.javascript.internal.EcmaError: ReferenceError: "cm" is not defined. (<Unknown source>#54) in <Unknown source> at line number 54
at com.sun.script.javascript.RhinoScriptEngine.invoke(RhinoScriptEngine.java:300)
at com.sun.script.javascript.RhinoScriptEngine.invokeFunction(RhinoScriptEngine.java:258)
at scripting.quest.QuestScriptManager.end(QuestScriptManager.java:149)
at net.server.channel.handlers.NPCMoreTalkHandler.handlePacket(NPCMoreTalkHandler.java:69)
at net.MapleServerHandler.messageReceived(MapleServerHandler.java:186)
at org.apache.mina.core.filterchain.DefaultIoFilterChain$TailFilter.messageReceived(DefaultIoFilterChain.java:690)
at …
> fix javax.script.ScriptException

- src/constants/ServerConstants.java
- src/net/server/channel/handlers/AdminChatHandler.java
- src/net/server/channel/handlers/GeneralChatHandler.java
- src/net/server/channel/handlers/MultiChatHandler.java
- src/net/server/channel/handlers/PetChatHandler.java
- src/net/server/channel/handlers/SpouseChatHandler.java
- src/tools/LogHelper.java
See https://github.com/ronancpl/HeavenMS/issues/293
> Server flag to log chat

- src/client/command/commands/gm1/GotoCommand.java
> Don't allow @goto in event maps

- src/net/server/channel/handlers/WhisperHandler.java
- src/tools/MaplePacketCreator.java
https://github.com/ronancpl/HeavenMS/issues/308
> Buddy find

- src/net/server/channel/handlers/InventorySortHandler.java
https://github.com/ronancpl/HeavenMS/issues/318
> Fix item sort deadlock

- src/net/server/channel/handlers/PartyOperationHandler.java
If you try to leave the party multiple times it can generate NPE
> Fix NPE in PartyOperationHandler

- scripts/npc/9201045.js
I don't know if this is just because I use Java 8, but the line gives me ClassCastException: Cannot cast Long to Integer
This PR should fix that
> Fix ClassCastException in 9201045

- sql/db_database.sql
- src/client/MapleCharacter.java
- src/net/server/Server.java
- src/net/server/worker/RankingLoginWorker.java
https://github.com/ronancpl/HeavenMS/issues/343
> Sort rankings by time of last EXP gain

- src/server/MapleStatEffect.java
https://github.com/ronancpl/HeavenMS/issues/357
> Don't deactivate Hyper Body buff before reapplying

- src/client/processor/SpawnPetProcessor.java
Fix https://github.com/ronancpl/HeavenMS/issues/345
> Fix Pet NPE

- src/client/MapleCharacter.java
> Small update correction

- scripts/npc/9010021.js
- src/client/MapleCharacter.java
- src/constants/ServerConstants.java
- src/tools/exceptions/NotEnabledException.java
> Handle reborns(rebirths) - set/get from db, flag to enable/disable and 1 basic NPC to handle it

- src/client/command/commands/gm3/StartEventCommand.java
> Allow everyone on the server to receive startevent message, not just the gm that starts it

- scripts/npc/9201033.js
- src/server/maps/MapleReactorFactory.java
* Fixed the "INVALID ID" while warping to certain MAPID with XML existed. (Thanks to Ronan)
* Started to fix the quest "Festival of Lights" - Now Simon warps you to the Shalom Temple in Happyville
> Reactory Factory Small Fix + Festival of Lights (NPC)

- scripts/npc/2101014.js
- scripts/npc/2101015.js
- scripts/npc/2101016.js
- scripts/npc/2101017.js
* Translated the NPC text into English
> Ariant PQ text translation

- README.md
Make it more clear that heavenms is open to becoming production-use ready but just isn't there right now. Encourage members to contribute.
> Make it more clear that production use is a goal

- src/client/command/CommandsExecutor.java
Prevents possible escape while in jail. (May have to also update other cash items to also prevent possible escape.)
> Disable commands while in jail.

- src/net/server/channel/handlers/MoveLifeHandler.java
- src/server/maps/AbstractAnimatedMapleMapObject.java
Fix for PR https://github.com/ronancpl/HeavenMS/pull/487.
Didn't notice one number, caused Zakum(at least) to fall through the floor and loop around.
> Bugfix for previous movement changes.
