.gitignore
Try merging this so that when you commit changes, you don't get the spam of the java .class files in the changes tab for people looking at what you changed in the code.
Also, did you see my comment about using HikariCP database pool instead of DBCP ? Just look at the benchmarks and reviews. https://github.com/brettwooldridge/HikariCP
Thanks for your contributions to the maple community Ronan!
=> Update gitignore so build file changes don't appear in commit diffs

src/tools/MaplePacketCreator.java
Fixed incorrect OPcode in CPQ that caused an error 38 when a player dies.
=> Typo in MaplePacketCreator.java

src/net/server/Server.java
Allows hotcode placement due to IDE's unable being able to find WZ files loading from debugging mode, for example, Eclipse or IntellJ.
=> WZPath Property Change

scripts/quest/4647.js
The following error was thrown when trying to complete the quest.
`javax.script.ScriptException: sun.org.mozilla.javascript.internal.EvaluatorException: Can't find method scripting.AbstractPlayerInteraction.teachSkill(number,number,number). (<Unknown source>#44) in <Unknown source> at line number 44`
Adding the missing argument fixes the issue and allows the quest to complete correctly.
=> Fixed teachSkill missing an argument on quest 4647

src/server/gachapon/GachaponItems.java, src/server/gachapon/MapleGachapon.java
Cache items so the array isn't returned multiple times and cache Gachapon.values() for maximum performance and stability
=> It's never too late to fix old code boys!

src/client/command/commands/gm0/StatDexCommand.java, src/client/command/commands/gm0/StatIntCommand.java, src/client/command/commands/gm0/StatLukCommand.java, src/client/command/commands/gm0/StatStrCommand.java
I think it should tell the player as this is a gm0 command if they don't fill in a valid number instead of just logging an error
Perhaps a good idea to do this for all commands
=> Fix NumberFormatException in stat commands

src/client/MapleCharacter.java
* Asked by Lost and solution suggested by Ronan in discord group.
* Using "target;" instead of "getWarpMap(target.getId());" to warp directly to the target intead of the target's map id.
* This allows GMs to patrol players inside instances.
=> Updated forceChangeMap for better GM Warpto

wz/Item.wz/Consume/0228.img.xml
Alternatively, could add a check so that the master level is not raised higher than possible by an item, instead of changing the WZ value.
=> Fix Hero's Will master level 10

src/net/server/PlayerStorage.java, src/net/server/world/World.java, src/server/life/MapleMonsterInformationProvider.java
You can get ConcurrentModificationException if a player is removed from PlayerStorage while another thread is looping through PlayerStorage.getAllCharacters()
```java
java.util.ConcurrentModificationException
at java.util.LinkedHashMap$LinkedHashIterator.nextEntry(LinkedHashMap.java:394)
at java.util.LinkedHashMap$ValueIterator.next(LinkedHashMap.java:409)
at net.server.worker.CharacterAutosaverWorker.run(CharacterAutosaverWorker.java:37)
at server.TimerManager$LoggingSaveRunnable.run(TimerManager.java:148)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:473)
at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
at …
```
=> Make PlayerStorage.getAllCharacters() return a copy

src/scripting/AbstractPlayerInteraction.java
This can present a problem for example if someone does the Aran skill quest while they already had the skill because of ServerConstants.USE_FULL_ARAN_SKILLSET
For example, they already had polearm mastery at level 20, but then they do the quest, so they end up with level 0, meaning 20 SP disappeared
=> Don't make skill level lower if they already have it

src/net/MapleServerHandler.java
MINA closes sessions automatically and does not call sessionClosed when an IOException is caught.
https://stackoverflow.com/questions/22796904/mina-2-0-7-sometimes-fail-to-notify-on-session-closed
=> Remove players on exceptionCaught with IOEXception. 

src/tools/MaplePacketCreator.java
fix the error when a monster's oid in map equals charId, (the item will drop from the error monster)
=> fix monster drop bug

src/client/command/commands/gm0/GmCommand.java
Fixed indexoutofbounds when calling gm without parameters
Allow capital letters in gm command parameters.
=> Command Changes

src/tools/BCrypt.java
Update jBCrypt from version 0.2 to 0.4 which resolves a security bug with character encoding and corrects an integer overflow bug.
Modify jBCrypt library to handle $2y$ hashes, which are produced by PHP's password_hash bcrypt function.  The original jBCrypt library only recognizes $2a$ hashes which makes it harder for a website CMS (content management system) to interface with the server's login and databases.
Credit to: Ariel Salomon for compatibility support of 2b, 2y, and 2x hashes https://github.com/anebril/jBCrypt/commit/fe143600107f3b7975f603ddfe843669421e2bf9#diff-61d1d5b7b3c721fac60702cf559d70aa
=> Update and Fix PHP bcrypt to login server bcrypt compatibility

configuration.ini, src/constants/ServerConstants.java, src/scripting/AbstractPlayerInteraction.java, src/scripting/event/EventManager.java, src/scripting/npc/NPCConversationManager.java, src/scripting/reactor/ReactorActionManager.java
Support Java 7 has been dropped since April *2015*, leaving installations of JDK7 vulnerable. We should make serious efforts to migrate.
This PR improves Java 8 support:
* Remove static tags from `AbstractPlayerInteraction` and `NPCConversationManager`.
* Remove `JAVA_8` configuration option en lieu of runtime detection.
* Uncomment instances I could find of JAVA_8 comments.
=> Fix Java 8 support

src/net/server/channel/handlers/CouponCodeHandler.java, src/tools/MaplePacketCreator.java
- Renamed method to `showCouponRedeemedItems()`
- In DB table `nxcode_items`, `type = 0` is now used for mesos.
=> Proper packet for showCouponRedeemedItem()

src/net/server/coordinator/MapleMatchCheckerCoordinator.java, src/net/server/coordinator/matchchecker/listener/MatchCheckerGuildCreation.java
Only players that were accepted before are disposed from this current `MapleMatchCheckingElement`; when disposing an entire match element, we should free all players from this match.
=> Fix stuck players when other player denies match request

scripts/npc/9020001.js
- NPC Name: Cloto
- Location: Kerning City PQ Stage 1 (Ligator hunt)
- In HeavenMS, she would tell the user they had the wrong number of passes, but not repeat the question.
- This was mainly a problem for those who missed the question the first time it was asked.
- With this fix, Cloto follows up with her 'wrong answer' speech, and repeats the proper question associated with the given player.
I'm new to all of this :sweat_drops:, so if this isn't the best way to do it, let me know and I hope to do it right next time! :grin: (such as adding it in a next window rather than being squishied into the same one) :cake:
=> Repeat question if user has wrong pass count

docs/leftover.txt, sql/db_database.sql, src/client/MapleCharacter.java, src/client/MapleClient.java, src/constants/ServerConstants.java, src/net/server/Server.java, src/net/server/channel/handlers/CashOperationHandler.java, src/net/server/channel/handlers/MoveDragonHandler.java, src/net/server/channel/handlers/MoveSummonHandler.java, src/net/server/channel/handlers/TransferNameHandler.java, src/net/server/channel/handlers/TransferNameResultHandler.java, src/net/server/channel/handlers/TransferWorldHandler.java, src/net/server/channel/handlers/UseCashItemHandler.java, src/net/server/handlers/login/LoginPasswordHandler.java, src/tools/FilePrinter.java, src/tools/MaplePacketCreator.java
- Some DB tables keep old names. (commented code)
- Doesn't check ban length (not tracked)~~, or most recent ban (no existing method)~~.
- Doesn't remove name change/world transfer cash item from inventory. (has to be done via SQL)
Also included :
- A few packets, including the ring purchase(I think) one.
- Small fix for GM jobs on non-GM accounts.
-Minor NPE fix. (Thanks BHB)
=> Added cash shop name changes and world transfers.

src/net/server/channel/handlers/BBSOperationHandler.java
They originally caused a BBS post to not send since the condition was true when the player correctly had the emoji icon in their inventory.
=> Fix cash shop bbsmojis

src/net/server/channel/handlers/AbstractDealDamageHandler.java
In Maplestory, there are three reflection buffs:
- Physical Reflect
- Magical Reflect
- Mixed Reflect (both combined)
Physical reflect would only reflect damage to physical users, Magical would only reflect to magical users, Mixed would reflect to both users.
In HeavenMS, the reflects are treated as an HP reflect and MP reflect, so the vanilla reflection mechanic was implemented here in this commit
I couldn't seem to recall any mobs that only had one or the other, so the best I could test with was Munin or Hugin (whichever's id was 8820005) but all three debuffs worked properly with that bird :grin:
=> Fix mob DR skills to GMS-like

src/client/MapleCharacter.java
Apologies for the commit name's incorrect issue reference, I don't know how to change its name :sob:
The original issue was that when the two following flags in ServerConstants are true, quests for players affected by the 1x exp rate retain the server's quest rate and do not receive 1x quest exp.
- USE_QUEST_RATE
- USE_ENFORCE_NOVICE_EXPRATE
This fix adds the check that enforces quest exp rate of 1x if USE_ENFORCE_NOVICE_EXPRATE is on.
=> Adds a check for when USE_ENFORCE_NOVICE_EXPRATE and USE_QUEST_RATE are both on

src/client/MapleClient.java, src/scripting/AbstractScriptManager.java, src/scripting/event/EventScriptManager.java, src/scripting/npc/NPCScriptManager.java, src/scripting/quest/QuestScriptManager.java, src/scripting/reactor/ReactorScriptManager.java
In order to make it easier to work with scripting, we need to clean up the base class:
* Remove references to `Invocable`. We require that we find a `NashornScriptEngine` (as finding another ScriptEngine is catastophic anyways). Since NashornScriptEngine is an `Invocable`, we don't need these extra casts.
* Remove potentially dangerous cache of `engine`.
=> Script engine refactor preparation

src/client/creator/CharacterFactoryRecipe.java
- In HeavenMS, new characters are given 4/4/4/4 STR/DEX/INT/LUK along with 0 AP, which is a shortage of 9AP
- In vanilla maplestory, dice rolls were made and counting the total AP (after dice rolls were removed, newborn character stats became 12/5/4/4 or something), there should be a sum of 25 total combined AP
- This fix gives newborn characters 9 AP to allocate for a total of 25 total combined AP
=> Give newly created characters proper AP count

wz/Quest.wz/Act.img.xml, wz/Quest.wz/Check.img.xml, wz/Quest.wz/QuestInfo.img.xml, wz/String.wz/Consume.img.xml, wz/String.wz/Etc.img.xml
- Fixes for broken line returns, typos, grammar, etc.
- Tweaked various item descriptions for consistency.
- Tweaked various item descriptions to make them more GMS-like.
- Added description of item effects in tooltips for Heartstopper and Smore.
- Changed description of Sunrise Dew to indicate 4050 MP recovery (was 4000).
- Various minor edits to text relating to quests and dialogue.
=> Overhaul of in-game text focusing on consumable items

Dockerfile, docker-compose.yml
What this PR has done:
- Update Dockerfile
- Upgrade the version of the openjdk image to 1.8.
- Add an add-on for waiting db service available.
- Add docker-compose.yml
- Make the services (server and db) run as normal process that using the ports (3306, 8484, 7575 .etc) on host directly.
- The service of server would start after the db is ready.
Why:
In order to host HeavenMS in any environment with docker and docker-compose by executing only one single command.
``` sh
$ docker-compose up
```
If source code or config is changed, you would have to re-build the image and re-create a container of it.
=> Add docker-compose support
